platform :ios, '16.0'

target 'iosApp' do
  use_frameworks!

  pod 'shared', :path => '../shared'

  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  pod 'FirebaseVertexAI'

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end

    target.shell_script_build_phases.each do |phase|
      if phase.shell_script.include?('gradlew')
        phase.shell_script = <<~SCRIPT
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
          export PATH="$JAVA_HOME/bin:$PATH"
          #{phase.shell_script}
        SCRIPT
      end
    end
  end
end
